namespace: default-namespace
services:
  api-gateway:
    name: api-gateway
    image: "gcr.io/cupra-cad/api-gateway:latest"
    replicas: 1
    minReplicas: 1
    maxReplicas: 5
    cpuTargetUtilization: 70
    nodePort: 30000
    port: 5000
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: GCP_PROJECT_ID
        value: "cupra-cad"
      - name: GCP_BUCKET
        value: "cupra-bucket"
      - name: GCP_ENV
        value: "prod"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/var/keys/service-account.json"
    volumes:
      - name: service-account-key
        mountPath: /var/keys
        readOnly: true
        secret:
          secretName: service-account-key
  property-management:
    name: property-management
    image: "gcr.io/cupra-cad/property-management:latest"
    replicas: 1
    minReplicas: 1
    maxReplicas: 5
    cpuTargetUtilization: 75
    nodePort: 30001
    port: 5001
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: GCP_PROJECT_ID
        value: "cupra-cad"
      - name: GCP_BUCKET
        value: "cupra-bucket"
      - name: GCP_ENV
        value: "prod"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/var/keys/service-account.json"
    volumes:
      - name: service-account-key
        mountPath: /var/keys
        readOnly: true
        secret:
          secretName: service-account-key

  parking-management:
    name: parking-management
    image: "gcr.io/cupra-cad/parking-management:latest"
    replicas: 1
    minReplicas: 1
    maxReplicas: 6
    cpuTargetUtilization: 65
    nodePort: 30002
    port: 5002
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: GCP_PROJECT_ID
        value: "cupra-cad"
      - name: GCP_BUCKET
        value: "cupra-bucket"
      - name: GCP_ENV
        value: "prod"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/var/keys/service-account.json"
    volumes:
      - name: service-account-key
        mountPath: /var/keys
        readOnly: true
        secret:
          secretName: service-account-key

  financial-management:
    name: financial-management
    image: "gcr.io/cupra-cad/financial-management:latest"
    replicas: 1
    minReplicas: 1
    maxReplicas: 4
    cpuTargetUtilization: 60
    nodePort: 30003
    port: 5003
    ports:
      - containerPort: 8080
    env:
      - name: PORT
        value: "8080"
      - name: GCP_PROJECT_ID
        value: "cupra-cad"
      - name: GCP_BUCKET
        value: "cupra-bucket"
      - name: GCP_ENV
        value: "prod"
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: "/var/keys/service-account.json"
    volumes:
      - name: service-account-key
        mountPath: /var/keys
        readOnly: true
        secret:
          secretName: service-account-key
