apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.namespace | default $.Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"  # Para GCP, ajusta según tu entorno
spec:
  rules:
    - host: frontend.tu-dominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
