apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace | default $.Release.Namespace }}
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
