{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /{{ .name }}/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          env:
            {{- if .env }}
            {{- range .env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
              {{- end }}
            {{- end }}
            {{- end }}
          volumeMounts:
            {{- if .volumes }}
            {{- range .volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath | default "/var/keys" }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- end }}
      volumes:
        {{- if .volumes }}
        {{- range .volumes }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secret.secretName }}
        {{- end }}
        {{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}
  minReplicas: {{ .minReplicas | default 1 }}
  maxReplicas: {{ .maxReplicas | default 10 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .cpuTargetUtilization | default 50 }}
---
{{- end }}
