{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    app: {{ .name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type:  NodePort
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
{{- end }}
