name: Deploy Frontend to Google Cloud Run

on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    environment: cupra-dev
    env:
      VITE_REACT_APP_API_URL: ${{ secrets.VITE_REACT_APP_API_URL }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: "./keys/service-account.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Set GCP project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 --build-arg VITE_REACT_APP_API_URL=https://my-backend-dev-965038707682.europe-west3.run.app -t my-frontend-dev ./frontend
          docker tag my-frontend europe-west3-docker.pkg.dev/cupra-cad/cupra-dev/my-frontend-dev

      - name: Push Docker image to Artifact Registry
        run: docker push europe-west3-docker.pkg.dev/cupra-cad/cupra-dev/my-frontend-dev

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-frontend-dev \
            --image europe-west3-docker.pkg.dev/cupra-cad/cupra-dev/my-frontend-dev \
            --platform managed \
            --region europe-west3 \
            --allow-unauthenticated \
            --set-env-vars VITE_REACT_APP_API_URL=https://my-backend-dev-965038707682.europe-west3.run.app
